token: "Input your bot token"
channels:
  announce: "Channel ID"
  chat: "Channel ID"
  verify: "Channel ID"
messages:
  welcome:
    enabled: true
    message:
      # 임베드 형식, 참고: https://cog-creators.github.io/discord-embed-sandbox/
      - title: "%discord% 님, 환영합니다!"
        url: "http://minecraft.net"
        description: "마인크래프트 서버에 오신 것을 환영합니다!"
        color: blue
        thumbnail: "https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/menu/menu-buy--reversed.gif"
      # 기본 형식
      - "%discord% 님, 환영합니다."
      - "본 서버는 Spicord 를 사용하고 있습니다."
      - "인증을 위해 `!인증 <게임닉네임>` 명령어를 입력해주세요!"
  server-on:
    enabled: true
    channel: announce
    message:
      title: "서버가 열렸습니다!"
      url: "http://minecraft.net"
      description: "서버가 열렸습니다."
      color: blue
      thumbnail: "https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/menu/menu-buy--reversed.gif"
  server-off:
    enabled: true
    channel: announce
    message:
      title: "서버가 닫혔습니다!"
      color: red
      description: "서버가 종료되었습니다. 마지막 동접자 수: %players%"
  player-chat:
    enabled: true
    channel: chat
    slow-mode: true
  player-kick:
    enabled: true
    channel: announce
    message:
      title: "사유: %reason%"
      description: "%player%(%uuid%)"
      url: "https://ko.namemc.com/search?q=%player%"
      thumbnail: "https://crafatar.com/avatars/%uuid%?overlay=true"
      color: orange
      author:
        title: "서버에서 추방되었습니다."
        icon: "https://crafatar.com/avatars/%uuid%?overlay=true"
  discord-chat:
    enabled: true
    channel: chat
    message: "&7[Discord] [%name%]: &f%message%"
    worlds: []
verification:
  enabled: true
  channel: [verify]
  command: "!인증"
  expire-second: 15
  before:
    player-restrict:
      - chat
      - build
      - pvp
      - move
  after:
    discord-role:
      - verified
    command:
      - "pex user %player% group set verified"
      - "whisper %player% 디스코드 &e%discord% &r로 인증되셨습니다."
