# 설정 영상 https://youtu.be/k2KegzmZOPU
token: "Input your bot token"
guild: "Guild ID"
channels:
  announce: "Channel ID"
  chat: "Channel ID"
  verify: "Channel ID"
  # ... 원하는 채널 계속 추가 가능
messages:
  welcome:
    # 임베드 형식, 참고: https://cog-creators.github.io/discord-embed-sandbox/
    - title: "%discord% 님, 환영합니다!"
      url: "http://minecraft.net"
      description: "마인크래프트 서버에 오신 것을 환영합니다!"
      color: blue
      thumbnail: "https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/menu/menu-buy--reversed.gif"
    # 기본 형식
    - "**%discord%** 님, 환영합니다."
    - "본 서버는 Spicord 를 사용하고 있습니다."
    - "인증을 위해 `!인증 <게임닉네임>` 명령어를 입력해주세요!"
  server-on:
    title: "서버가 열렸습니다!"
    url: "http://minecraft.net"
    description: "서버가 열렸습니다."
    color: blue
    thumbnail: "https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/menu/menu-buy--reversed.gif"
  server-off:
    title: "서버가 닫혔습니다!"
    color: red
    description: "서버가 종료되었습니다. 마지막 동접자 수: %players%"
  player-kick:
    title: "사유: %reason%"
    description: "%player%(%uuid%)"
    url: "https://ko.namemc.com/search?q=%player%"
    thumbnail: "https://crafatar.com/avatars/%uuid%?overlay=true"
    color: orange
    author:
      title: "서버에서 추방되었습니다."
      icon: "https://crafatar.com/avatars/%uuid%?overlay=true"
  player-chat: "**%display-name%**: %message%"
  verify-usage: "명령어 사용법: `%command% 게임닉네임`"
  verify-code:
    - "인증코드: `%code%`"
    - "위 인증코드를 마인크래프트 서버 채팅창에"
    - "**%player%** 계정으로 입력하세요!"
  player-offline: "**%name%** 은(는) 접속 중인 플레이어가 아닙니다!"
  verify-expired: "%seconds% 초가 지나, 인증이 만료되었습니다. 다시 시도해주세요."
  already-verified: "이미 **%uuid%** 로 인증되어있습니다."
  verify-success: "인증되었습니다! 연동 계정: **%discord%**"
  verify-failed: "인증에 실패했습니다. 다시 시도해주세요"
  verify-cooldown: "%seconds% 초 후 다시 시도해주세요."
  # ... 원하는 메세지 계속 추가 가능
features:
  welcome:
    enabled: true
    message: welcome
  server-on:
    enabled: true
    channel: announce
    message: server-on
  server-off:
    enabled: true
    channel: announce
    message: server-off
  player-kick:
    enabled: true
    channel: announce
    message: player-kick
  player-chat:
    enabled: true
    channel: chat
    fake-profile: true
    join-quit: true
    join-message: "%display-name% joined the game."
    quit-message: "%display-name% left the game."
    ignore-cancel: true
    message: player-chat
  discord-chat:
    enabled: true
    channel: chat
    message: "&7[Discord] [%name%]: &f%message%"
    worlds: []
verification:
  enabled: true
  channel: verify
  command: "!인증"
  expire-seconds: 20
  cooldown-seconds: 40
  delete-if-quit: false
  before:
    player-restrict: [chat, build, pvp, move, item]
  after:
    name-sync: false
    discord-name-format: "%name%"
    discord-role:
      - verified
    command:
      - "give %player% apple 1"
      - "tell %player% 디스코드 &e%discord% &r로 인증되셨습니다."
